# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/jerrychen/Downloads/openGLredBook9th-master/lib/glfw/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/jerrychen/Downloads/openGLredBook9th-master/lib/glfw/cmake_uninstall.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/jerrychen/Downloads/openGLredBook9th-master/lib/glfw/src/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/jerrychen/Downloads/openGLredBook9th-master/lib/glfw/src/glfw3.pc.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/jerrychen/Downloads/openGLredBook9th-master/lib/glfw/src/glfw3Config.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/jerrychen/Downloads/openGLredBook9th-master/lib/glfw/src/glfw_config.h.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.18.1/share/cmake/Modules/BasicConfigVersion-SameMajorVersion.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.18.1/share/cmake/Modules/CMakePackageConfigHelpers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.18.1/share/cmake/Modules/CheckCSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.18.1/share/cmake/Modules/CheckIncludeFile.c.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.18.1/share/cmake/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.18.1/share/cmake/Modules/CheckLibraryExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.18.1/share/cmake/Modules/FindOpenGL.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.18.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.18.1/share/cmake/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.18.1/share/cmake/Modules/FindThreads.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.18.1/share/cmake/Modules/WriteBasicConfigVersionFile.cmake))

/Users/jerrychen/Downloads/openGLredBook9th-master/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.18.1/bin/cmake -H/Users/jerrychen/Downloads/openGLredBook9th-master -B/Users/jerrychen/Downloads/openGLredBook9th-master
